name: Deploy Spelserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Uppdatera kod i webbserver-spel
        run: |
          cd /opt/webbserver-spel
          git pull

      - name: Kompilera om Java-filer
        run: |
          cd /opt/webbserver-spel
          find . -name "*.java" > sources.txt
          javac -cp guessGames.jar @sources.txt

